### ISSUE TITLE
More than 1 dataType

### ISSUE THREAD

**Issue by maxinnn1** [jonathanfiss/convert-json-to-raml-datatype#1]
Hellow, this is my first issue in GitHub, sorry if its a bit messy.

Im using this tool for helping me creating dataType, iv found a bug while forming a dataType where 1 field have more than 1 dataType. Let me show you a example.

I will use this Json

```
{
   "additionalInformation":[
      {
         "attribute":"marcaRemesadora",
         "value":"DWU"
      },
      {
         "attribute":"accountType",
         "value":"SAVINGS"
      },
      {
         "atribute":"rate",
         "value":1
      }
   ]
}
```

This is the result that it gives me

```
#%RAML 1.0 DataType 
type: object
properties:
  additionalInformation:
    type: array
    items:
      type: object
      properties:
        attribute:
          type: string
          example: marcaRemesadora
        value:
          type:
            - string
            - integer
          example: DWU
        atribute:
          type: string
          example: rate
```

If i put this in Design Center it get an error

![Captura desde 2023-04-25 13-05-24](https://user-images.githubusercontent.com/1350429/234336718-82bd6c7f-4a5d-49cf-8976-14f3eba9b4d8.png)

Iv found a way to fix it

![Captura desde 2023-04-25 13-06-14](https://user-images.githubusercontent.com/1350429/234336950-7a5656ad-6f87-4663-9e32-3db1eef57b61.png)

Il post here the code if you need it 

```
#%RAML 1.0 DataType 
type: object
properties:
  additionalInformation:
    type: array
    items:
      type: object
      properties:
        attribute:
          type: string
          example: marcaRemesadora
        value:
          type:
            - string | integer
          example: DWU
        atribute:
          type: string
          example: rate
```
Hope this helps you. Thanks a lot for the tool it helps reducing my time whille creating a raml.

**Comment by andersoal** [comment]
I think that this can be simplified as just `type: string | integer`

```yaml
#%RAML 1.0 DataType 
type: object
properties:
  additionalInformation:
    type: array
    items:
      type: object
      properties:
        attribute:
          type: string
          example: marcaRemesadora
        value:
          type: string | integer
          example: DWU
        atribute:
          type: string
          example: rate
```
